### ISSUE TITLE
nested exception is java.lang.UnsupportedOperationException: io.lettuce.core.output.ValueOutput does not support set(long)

### ISSUE THREAD

**Issue by Memorydoc** [redis/lettuce#2831] opened 2024-04-18 07:45 UTC
Our service encountered ValueOutput does not support set(long) exception, which was automatically recovered after service restart. Strange scenario. How do we solve this?

<img width="1597" alt="image" src="https://github.com/redis/lettuce/assets/34032596/740ff8b0-b8e7-4d1d-95ae-825695e30c45">

**Comment by tishun** [comment] 2024-04-18 10:52
Hey @Memorydoc ,
from the exception name (org.springframework.data.redis.RedisSystemException) I can only assume you are having issue with the [Spring Data Redis ](https://github.com/spring-projects/spring-data-redis) and not the Lettuce driver itself? 

Anyway to understand the issue better we will need more information like a complete stacktrace or a sample of the code that ptoduces this issue.

**Comment by ShepherdZFJ** [comment] 2024-04-29 02:36
I encountered the same problem when upgrading from Spring boot2.3.4 to 2.7.0。
The code example is as follows：
`   @Test
    public void test() {
        StringBuilder lua = new StringBuilder();
        lua.append("local c");
        lua.append("\nc = redis.call('get',KEYS[1])");
        lua.append("\nif c and tonumber(c) > tonumber(ARGV[1]) then");
        lua.append("\nreturn c;");
        lua.append("\nend");
        lua.append("\nc = redis.call('incr',KEYS[1])");
        lua.append("\nif tonumber(c) == 1 then");
        lua.append("\nredis.call('expire',KEYS[1],ARGV[2])");
        lua.append("\nend");
        lua.append("\nreturn c;");
        int limitCount = 10;
        int limitPeriod = 3;
        List<String> keys = new ArrayList<>();
        keys.add("kk");
        RedisScript<Number> redisScript = new DefaultRedisScript<>(lua.toString(), Number.class);
        Number count = stringRedisTemplate.execute(redisScript, keys, String.valueOf(limitCount), String.valueOf(limitPeriod));
        System.out.println(count);
    }`

The debug code enters the execute method of the DefaultScriptExecutor class of spring-data-redis：
`	public <T> T execute(final RedisScript<T> script, final RedisSerializer<?> argsSerializer,
			final RedisSerializer<T> resultSerializer, final List<K> keys, final Object... args) {
		return template.execute((RedisCallback<T>) connection -> {
			final ReturnType returnType = ReturnType.fromJavaType(script.getResultType());
			final byte[][] keysAndArgs = keysAndArgs(argsSerializer, keys, args);
			final int keySize = keys != null ? keys.size() : 0;
			if (connection.isPipelined() || connection.isQueueing()) {
				// We could script load first and then do evalsha to ensure sha is present,
				// but this adds a sha1 to exec/closePipeline results. Instead, just eval
				connection.eval(scriptBytes(script), returnType, keySize, keysAndArgs);
				return null;
			}
			return eval(connection, script, returnType, keySize, keysAndArgs, resultSerializer);
		});
	}`

In version 2.3.4, the ReturnType is Integer and IntegerOutPut will be generated, but in version 2.7.0, the ReturnType is VALUE and generates ValueOutPut, resulting in the above error, so I think ValueOutPut should support the processing of Number, which can solve this problem.

**Comment by tishun** [comment] 2024-05-22 11:03
@Memorydoc , @ShepherdZFJ ,
Seems to me this is deffinetly an issue with [spri](https://github.com/spring-projects/spring-data-redis), perhaps sometihng like https://github.com/spring-projects/spring-data-redis/issues/2908

This project works on the underlying driver and - unless the driver is the problem - there is nothing to be done in Lettuce.

Closing this, please reopen if you have some indications that the issue is in the Lettuce code.

**Closed** 2024-05-22 11:03 UTC
Labels: status: waiting-for-feedback

**Comment by wangchengming666** [comment] 2025-01-10 15:17
Caused by: java.lang.UnsupportedOperationException: io.lettuce.core.output.ValueOutput does not support set(long)
	at io.lettuce.core.output.CommandOutput.set(CommandOutput.java:107)
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:774)
	at io.lettuce.core.protocol.RedisStateMachine.handleInteger(RedisStateMachine.java:409)
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:205)
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:339)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:300)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:840)
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:791)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:765)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:657)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:597)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted

**Comment by tishun** [comment] 2025-01-11 09:21
> @tishun hi, stack as blow, could you help look this issue.

Let's continue the discussion in #3121 which you opened

**Comment by tishun** [comment] 2025-01-13 09:07
> I encountered the same problem when upgrading from Spring boot2.3.4 to 2.7.0 The code example is as follows：
> 
> ```java
>    @Test
>     public void test() {
>         StringBuilder lua = new StringBuilder();
>         lua.append("local c");
>         lua.append("\nc = redis.call('get',KEYS[1])");
>         lua.append("\nif c and tonumber(c) > tonumber(ARGV[1]) then");
>         lua.append("\nreturn c;");
>         lua.append("\nend");
>         lua.append("\nc = redis.call('incr',KEYS[1])");
>         lua.append("\nif tonumber(c) == 1 then");
>         lua.append("\nredis.call('expire',KEYS[1],ARGV[2])");
>         lua.append("\nend");
>         lua.append("\nreturn c;");
>         int limitCount = 10;
>         int limitPeriod = 3;
>         List<String> keys = new ArrayList<>();
>         keys.add("kk");
>         RedisScript<Number> redisScript = new DefaultRedisScript<>(lua.toString(), Number.class);
>         Number count = stringRedisTemplate.execute(redisScript, keys, String.valueOf(limitCount), String.valueOf(limitPeriod));
>         System.out.println(count);
>     }
> ```
> 
> The debug code enters the `execute` method of the `DefaultScriptExecutor` class of `spring-data-redis`：
> 
> ```java
> public <T> T execute(final RedisScript<T> script, final RedisSerializer<?> argsSerializer,
> 			final RedisSerializer<T> resultSerializer, final List<K> keys, final Object... args) {
> 		return template.execute((RedisCallback<T>) connection -> {
> 			final ReturnType returnType = ReturnType.fromJavaType(script.getResultType());
> 			final byte[][] keysAndArgs = keysAndArgs(argsSerializer, keys, args);
> 			final int keySize = keys != null ? keys.size() : 0;
> 			if (connection.isPipelined() || connection.isQueueing()) {
> 				// We could script load first and then do evalsha to ensure sha is present,
> 				// but this adds a sha1 to exec/closePipeline results. Instead, just eval
> 				connection.eval(scriptBytes(script), returnType, keySize, keysAndArgs);
> 				return null;
> 			}
> 			return eval(connection, script, returnType, keySize, keysAndArgs, resultSerializer);
> 		});
> 	}
> ```
> 
> In version 2.3.4, the ReturnType is `Integer` and `IntegerOutPut` will be generated, but in version 2.7.0, the ReturnType is `VALUE `and generates `ValueOutPut`, resulting in the above error, so I think `ValueOutPut` should support the processing of `Number`, which can solve this problem.

Hey @ShepherdZFJ ,

Have you tried running this script with some other driver / method?
What I get is 

> ERR value is not an integer or out of range script: 953804d07099a2cd2aed5c4d9808174147ed9abb, on @user_script:8.

I do agree though that the message from the Lettuce driver does not help identify the problem.
