### ISSUE TITLE
enablePeriodicRefresh has problematic behavior when service is shut down(close)

### ISSUE THREAD

**Issue by Kvicii** [redis/lettuce#3089] opened 2024-12-18 14:19 UTC
#### Current Behavior

For example: I have 2 classes, A and B, and the close method is as follows.
A will cycle through multiple RedisSenders (B) and finally release ClientResources. At the same time, `ClusterTopologyRefreshOptions` is set as follows:

```java
.enablePeriodicRefresh(10 seconds)
.enableAllAdaptiveRefreshTriggers()
.closeStaleConnections(true)
.dynamicRefreshSources(true)
```

I found that it might be because the netty thread was not closed in time, and the following error occurred:

<img width="1228" alt="Screenshot 2024-12-18 at 22 14 35" src="https://github.com/user-attachments/assets/8a9f686b-6238-40cc-9d87-71daf59c9e33" />
<img width="1297" alt="Screenshot 2024-12-18 at 22 14 43" src="https://github.com/user-attachments/assets/394876b4-e95a-498b-8385-023a86bad89e" />

```java
// A
public void close() {
    for (RedisSender sender : RedisSender List) {
        sender.close();
    }

    if (clientResources != null) {
        clientResources.shutdown();
    }
}

// B RedisSender
public void close() {
    StatefulRedisClusterConnection<String, byte[]>.close();
    RedisCluster.close();
}
```

#### Expected behavior/code
After the ClientResources are closed, the tasks being processed should be discarded

#### Environment

- Lettuce version(s): 6.3.2-RELEASE

**Comment by tishun** [comment] 2024-12-21 12:04
This seems to be the same issue as the one described in #2904

**Comment by Karonazaba** [comment] 2024-12-23 06:58
@tishun yes, but I'm not sure if it can be fixed soon, as [#2985](https://github.com/redis/lettuce/pull/2985) mentioned, I'm not sure if it works.

**Comment by Kvicii** [comment] 2024-12-23 06:59
@tishun yes, but I'm not sure if it can be fixed soon, as https://github.com/redis/lettuce/pull/2985 mentioned, I'm not sure if it works.

**Comment by tishun** [comment] 2024-12-23 10:34
Closing in favor of https://github.com/redis/lettuce/issues/2904
Let's continue the discussion there.

If this is another problem, please reopen and describe how it is different so we can try and address it too.

**Comment by tishun** [comment] 2024-12-23 10:53
> @tishun yes, but I'm not sure if it can be fixed soon, as #2985 mentioned, I'm not sure if it works.

Not fixed yet. 

How big of a problem is it for you? Because it seems to me like it should not have a big effect on the application, besides the log messages?

**Comment by tishun** [comment] 2024-12-23 11:00
> > @tishun yes, but I'm not sure if it can be fixed soon, as #2985 mentioned, I'm not sure if it works.
> 
> Not fixed yet.
> 
> How big of a problem is it for you? Because it seems to me like it should not have a big effect on the application, besides the log messages?

To elaborate more on my question:
- if there is a functional regression caused by this problem then we would increase it's priority
- if not I would have to postpone it for now, as there are actual functional bugs that are with higher priority

As always if you believe you can contribute a solution please send out a PR with your idea.

**Comment by Kvicii** [comment] 2024-12-24 02:55
@tishun No significant impact has been found so far, but for a stable service, some error logs should be avoided as much as possible.

**Comment by tishun** [comment] 2024-12-25 07:36
Thanks @Kvicii

**Closed** 2024-12-25 07:36 UTC
Labels: status: waiting-for-feedback
