### ISSUE TITLE
lettuce doesnt queue commands to buffer in a failover scenario

### ISSUE THREAD

**Issue by ALSowjanya** [redis/lettuce#1426] opened 2020-09-23 12:21 UTC
## Bug Report
We have triggered redis failover api in AWS elasticache redis, while the client is in a K8 environment
From configuration point of view, we have
- auto reconnect is enabled
- disconnect behaviour is set as default(accept command when disconnected) 
- request-queue-size is marked at 200(higher than the commands which we have triggered)
- adaptive-refresh-triggers-timeout-in-seconds as 30secs
- All triggers are enabled for adaptive refresh
- periodic refresh is disabled
- cancel commands on reconnect failure is false
- suspend reconnect on protocol failure is false

#### Current Behavior
When we trigger failover from AWS console. Though in the prev logs, channel was closed/ channel was inactive, still the commands are triggered on redis server and below exception was observed.
**logs:**
**logs**:
[36m08:22:36.486[0;39m [1;30m[lettuce-nioEventLoop-4-2][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.CommandHandler[0;39m - [channel=0x4f03c02c, /10.0.30.51:50644 -> redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379, chid=0x48] channelInactive() done
[36m08:22:36.486[0;39m [1;30m[lettuce-nioEventLoop-4-2][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.ConnectionWatchdog[0;39m - [channel=0x4f03c02c, /10.0.30.51:50644 -> redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379, last known addr=redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379] channelInactive()
[36m08:22:36.486[0;39m [1;30m[lettuce-nioEventLoop-4-2][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.ConnectionWatchdog[0;39m - [channel=0x4f03c02c, /10.0.30.51:50644 -> redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379, last known addr=redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379] Reconnect scheduling disabled
[36m08:22:36.486[0;39m [1;30m[lettuce-nioEventLoop-4-2][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.CommandHandler[0;39m - [channel=0x4f03c02c, /10.0.30.51:50644 -> redisforfailovervalidation-0003-002.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.34.140:6379, chid=0x48] channelUnregistered()
[36m08:22:36.487[0;39m [1;30m[lettuce-eventExecutorLoop-1-3][0;39m [39mDEBUG[0;39m [35mio.lettuce.core.RedisChannelHandler[0;39m - closeAsync()
[36m08:22:36.487[0;39m [1;30m[lettuce-eventExecutorLoop-1-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.DefaultEndpoint[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, epid=0x37] closeAsync()
[36m08:22:36.487[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.ConnectionWatchdog[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, last known addr=redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379] userEventTriggered(ctx, SslCloseCompletionEvent(java.nio.channels.ClosedChannelException))
[36m08:22:36.487[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.CommandHandler[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, chid=0x47] channelInactive()
[36m08:22:36.487[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.DefaultEndpoint[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, epid=0x37] deactivating endpoint handler
[36m08:22:36.487[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.CommandHandler[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, chid=0x47] channelInactive() done
[36m08:22:36.488[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.ConnectionWatchdog[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, last known addr=redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379] channelInactive()
[36m08:22:36.488[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.ConnectionWatchdog[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, last known addr=redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379] Reconnect scheduling disabled
[36m08:22:36.488[0;39m [1;30m[lettuce-nioEventLoop-4-3][0;39m [39mDEBUG[0;39m [35mi.l.core.protocol.CommandHandler[0;39m - [channel=0x3a3a51d2, /10.0.30.51:50608 -> redisforfailovervalidation-0002-003.redisforfailovervalidation.run3wt.use1.cache.amazonaws.com/10.0.8.79:6379, chid=0x47] channelUnregistered()
[36m08:22:36.490[0;39m [1;30m[lettuce-eventExecutorLoop-1-3][0;39m [39mDEBUG[0;39m [35mi.l.c.c.PooledClusterConnectionProvider[0;39m - closeStaleConnections() count before expiring: 10
[36m08:22:36.490[0;39m [1;30m[lettuce-eventExecutorLoop-1-3][0;39m [39mDEBUG[0;39m [35mi.l.c.c.PooledClusterConnectionProvider[0;39m - closeStaleConnections() count after expiring: 10
<details>
<summary>Stack trace</summary>
```java
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51)
at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:120)
at io.lettuce.core.cluster.ClusterFutureSyncInvocationHandler.handleInvocation(ClusterFutureSyncInvocationHandler.java:123)
at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
at com.sun.proxy.$Proxy17.set(Unknown Source)
at com.pega.fnx.datagrid.serviceredis.client.lettuce.commands.LettuceKeyValueCache.executeSetCommand(LettuceKeyValueCache.java:62)
... 20 common frames omitted
```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java
        RedisClusterClient client = RedisClusterClient.create(clientResource.get(), redisURI.get());
        client.setOptions(clientOptions.get());
        StatefulRedisClusterConnection connection =  clusterClient.connect(RedisCodec.of(
                new StringCodec(StandardCharsets.UTF_8),
                new ByteArrayCodec()));
         RedisClusterCommands clusterCommands = clusterClientConnection.sync();
         SetArgs setArgs = SetArgs.Builder.px(60000); //1min
         String setCmdStatus = clusterCommands.set("key", "value".toByteArray(), setArgs);

```

</details>

#### Expected behavior/code
I was expecting that the commands sent during the failover time will be queued to the buffer and will be executed once server is connected back. But that was not the case, command was sent to the node even though the connection was not established.

#### Environment

- Lettuce version(s): 5.3.0.RELEASE
- Redis version: AWS Elasticache Redis 5.0.6

**Comment by mp911de** [comment] 2020-09-23 13:54
Commands are queued during a disconnect but that doesn't pause the timeout scheduler. From a caller side, you don't want that the duration for a command is depending on the fact whether the connection is connected or disconnected. Instead, you want a reliable timeout cap so you can reason about service levels and a maximal latency.

If the server comes back during the configured timeout of one minute, the command will be re-sent. If the server is disconnected for longer than 1 minute, your application will see timeouts.

**Comment by ALSowjanya** [comment] 2020-09-24 09:08
> From a caller side, you don't want that the duration for a command is depending on the fact whether the connection is connected or disconnected. Instead, you want a reliable timeout cap so you can reason about service levels and a maximal latency.
yes, and should be able to tell if the command can be retriggered from caller end or not.
> 
> If the server comes back during the configured timeout of one minute, the command will be re-sent. If the server is disconnected for longer than 1 minute, your application will see timeouts.
Is the above described behaviour already in place. And will the commands which are queued be removed once timeout is reached or will the command be in the queue even after the timeout.

**Comment by mp911de** [comment] 2020-09-28 09:36
> I have tested this behaviour. I see that caller will receive timeout exception, but command will still be processed once the connection is established after the timeout period as well. Do we have a way to cancel the command as well when timeout is reached. Because this is giving a wrong message to the caller.

Commands that time out are completed either exceptionally with `TimeoutException` or get cancelled when using the synchronous API. `DefaultEndpoint` removes cancelled/completed commands to avoid replaying completed/cancelled commands.

Can you provide a small reproducer if you still can observe the problem?

**Comment by ALSowjanya** [comment] 2020-09-30 06:26
I have created a sample app to reproduce the issue. You can run the program, you should see below messages 
```
"Enter
1.perform put operation 2. terminate "
```
choose 1, it will create a connection and update the "key" in redis cluster. Slot number will be available in the log as shown below
```
Performing put operation
Key will be put in slot: 12539
```
Now you can connect to master node of this slot, and flush this key(remove the key), check the client list, client name is testClient. Now you can kill the client. Auto reconnect is enabled with lower bound as 30 secs. And command timeout as 5 secs. So now again, immediately perform the put operation. Since connection is disconnected. We will get timeout exception after 5 secs. And after 30 secs we see logs stating reconnection established. After connection is reestablished, you can check for keys in redis master node. You should be seeing that key is available. Let me know if you need more details
[micronautapp.zip](https://github.com/lettuce-io/lettuce-core/files/5303449/micronautapp.zip)

**Comment by ALSowjanya** [comment] 2020-10-06 10:12
@mp911de Could get some time to look into this. Can we mark the issue as bug, since I have also provided a reproducible steps and app ?

**Comment by tishun** [comment] 2024-12-08 14:20
Hey @ALSowjanya , 

I see this is an issue from 2020 - did you manage to solve the problem? Have you tried newer versions of the driver?

**Comment by tishun** [comment] 2024-12-23 12:38
Hey @ALSowjanya ,

I've used your example and it works exactly how you described, but this behaviour is expected:

1. You send a command to the server
2. You flush the database and kill the client connection from another client
3. You attempt to send a command again

What I see locally is that the driver re-establishes connection and sends the command.
I never see a timeout being thrown for the command.

If I do change the timeout to some very low value, e.g. 1 ms (to quick for the reconnect to succeed) I get the TimeoutException and then I see no modifications in the database.

I am closing this for now because I can't see a problem with the driver.

**Closed by tishun** 2024-12-23 12:38 UTC
Labels: for: team-attention, status: waiting-for-triage, status: mre-available
