### ISSUE TITLE
Add support for Redis 7 sharded Pub/Sub

### ISSUE THREAD

**Issue by mp911de** [redis/lettuce#1984] opened 2022-02-02 09:53 UTC
See https://redis.io/topics/pubsub#sharded-pubsub

For the Cluster Pub/Sub, we likely need to only consider keys for routing as Cluster Pub/Sub intentionally drops the slot hash calculation.

**Comment by Dmdl** [comment] 2022-11-20 02:45
Do we know when will lettuce support sharded Pub/Sub?

**Comment by jthacker2** [comment] 2022-12-07 05:24
want to use this as well, any plan for support?

**Comment by prashanth-srinivasan1** [comment] 2023-03-17 22:51
@mp911de is there any plan to implement this in the near future?

**Comment by adamsau** [comment] 2023-06-28 10:40
any updates?

**Comment by adamsau** [comment] 2023-07-17 10:47
> This feature requires a bit of design. While there is an intent to implement this, there's no time-line as this project is maintained in our spare time.

is it possible to submit a PR on this? any specific design decision we need to be aware? @mp911de

**Comment by mp911de** [comment] 2023-07-18 06:46
Happy to review a pull request.

**Comment by tishun** [comment] 2024-04-01 11:43
The sharded pub/sub should be handled by

- #2758 
- #2757 
- #2759 
- #2756 
- #2776 

Duplicate of #2762

**Closed** 2024-04-01 11:44 UTC
Labels: type: enhancement
